version: '3'
services:
  myproj_redis:
    image: redis:4.0.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  ucigrab_controller:
    image: ucigrab:latest
    command: uvicorn api:app --host 0.0.0.0 --port 5057
    ports:
      - "5057:5057"
    depends_on:
      - ucigrab_redis
    links:
      - ucigrab_redis
  ucigrab_worker:
    image: ucigrab:latest
    command: rq worker --url redis://ucigrab_redis:6379 my_queue
    depends_on:
      - ucigrab_redis
    links:
      - ucigrab_redis¸A
  ucigrab_interface:
    image: ucigrab:latest
    command: rq worker --url redis://ucigrab_redis:6379 my_queue
    depends_on:
      - ucigrab_redis
    links:
      - ucigrab_redis¸A
  ucigrab_printr:
    image: ucigrab:latest
    command: rq worker --url redis://ucigrab_redis:6379 my_queue
    depends_on:
      - ucigrab_redis
    links:
      - ucigrab_redis¸A